[project]
name = "dlss-2025"
version = "0.1.0"
description = "Deep Learning Summer School 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tensorflow-macos>=2.16.2",
    "tensorflow-metal>=1.2.0",
]
